### ISSUE TITLE
After hiding with Hotkey reopening is not possible

### ISSUE THREAD

**Issue by pstorch** [marcharding/mintty-quake-console#4]
I defined a Hotkey to open the console. After hitting the Hotkey again to hide it, it can't be opened again.
I have to click on "reload" on the tray icon. Then I can use the Hotkey again to open it.

**Comment by marcharding** [comment]
You should really switch to the https://github.com/lonepie/mintty-quake-console fork. I merely started this for fun and do not maintain it anymore.

**Comment by pstorch** [comment]
I already saw the fork. Thanks.
